<div id="<?=$this->instanceId?>" class="widget movable collapsable removable closeconfirm">
	<div class="widget-header">  
		<h2>Testy</h2>  
	</div>
	<div class="widget-content">
		<ul>
			<li><a href="<?=$this->baseUrl('/test/group/1')?>">Users</a></li>
			<li><a href="<?=$this->baseUrl('/test/group/2')?>">Parameters</a></li>
			<li><a href="<?=$this->baseUrl('/test/group/3')?>">Products</a></li>
			<li><a href="<?=$this->baseUrl('/test/rest-products')?>">Products REST</a></li>
		</ul>
	</div>
</div>