<div id="<?=$this->instanceId?>" class="widget movable collapsable removable editable closeconfirm">

	<div class="widget-header">  
		<h2>Lorem ipsum</h2>  
	</div>
	<div class="widget-content">
		 Nunc tincidunt laoreet metus sit amet mollis. Suspendisse potenti. Vivamus quis quam eget odio ultricies consectetur ut nec erat. Maecenas imperdiet arcu quis urna egestas pretium. Morbi egestas varius euismod. Ut purus diam, tristique vitae fermentum ut, pharetra ac nisl. Integer nec sapien nulla, sed tincidunt diam. Morbi lacus quam, sollicitudin a aliquam vel, feugiat vitae mi. Etiam sagittis, quam at accumsan vulputate, quam leo elementum nunc, id volutpat elit mauris vitae lectus. Pellentesque ac dolor sed nibh aliquam facilisis.
	</div>

	<div id="<?=$this->instanceId?>-editbox" class="widget-editbox">
		<form name="widgetEditForm<?=$this->instanceId?>" method="POST">
			parametr 1: <input name="param1" value="<?=$this->params['param1']?>"/><br />
			parametr 2: <input name="param2" value="<?=$this->params['param2']?>"/>
		</form>
	</div>
	
</div>