<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Zero9gravity Admin</title>
	
	<link type="text/css" href="<?=$this->baseUrl('admin/css/main.css')?>" rel="stylesheet" />
	<link type="text/css" href="<?=$this->baseUrl('admin/css/colors/dark_blue.css')?>" rel="stylesheet" />
	<link type="text/css" href="<?=$this->baseUrl('admin/css/superfish.css')?>" rel="stylesheet" />
	
	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-1.4.2.min.js')?>"></script>    
	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery-ui-1.8.1.custom.min.js')?>"></script>

	<script type="text/javascript" src="<?=$this->baseUrl('js/ckeditor/ckeditor.js')?>"></script> 
	<script type="text/javascript" src="<?=$this->baseUrl('js/ckeditor/adapters/jquery.js')?>"></script>

	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.hoverIntent.minified.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/superfish.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.tools.min.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.simplemodal.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.notifyBar.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.tipsy.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.validate.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/enhance.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/excanvas.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/visualize.jQuery.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jQuery.collapsible.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/jquery.autoSuggest.packed.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('admin/js/platinum-admin.js')?>"></script>

	<script type="text/javascript" src="<?=$this->baseUrl('js/jquery.zend.jsonrpc.js')?>"></script>
	<script type="text/javascript" src="<?=$this->baseUrl('js/json2.js')?>"></script>
	
	<script type="text/javascript" src="<?=$this->baseUrl('js/zgrid/zgrid.js')?>"></script>
	
	<script type="text/javascript">
		// rpc server
		var client = jQuery.Zend.jsonrpc({url: '<?=$this->baseUrl('rpc')?>'});
		$(document).ready(function(){
			$('a#power').click(function(e){
				e.stopPropagation();
				client.logout();
				location.reload();
				return false;
			});
			<?=$this->message()?>
		});
	</script>
</head>

<body>

<div id="header">
	<div id="header-top">
		<div id="logo">
			<h1>Zergo9ravity Admin</h1>
			<span id="slogan">lorem ipsum dolor asmet!</span> 
		</div>
		<!-- end logo -->
		<div id="login-info">
			<img src="<?=$this->baseUrl('admin/images/icons/user.png')?>" alt="profile" id="profile">
			<p id="top"><span id="name"><?=$this->user()->getName().' '.$this->user()->getSurname()?></span><br>
			<span id="links">
			<a title="click to see the messages!" href="#" id="message-link">
				<?php if ($this->user()->getNewMessagesNumber()): ?>
					<span id="message-count"><?=$this->user()->getNewMessagesNumber()?></span> nowych wiadomosści.
				<?php else: ?>
					nie masz nowych wiadomości
				<?php endif ?>
			</a></span></p>
			<div id="messages-box">
				<h4>Messages</h4>
				<h5><a href="#" id="new-message">New Message</a></h5>
				<hr>
				<ul id="messages">
					<li class="new"><a href="#">
					<img src="images/icons/sender.png" alt="user">
					<span class="sender">John Doe</span>
					<span class="description">Hi this is just a description...</span>
					<span class="date">20 minutes ago...</span> </a></li>
					<li><a href="#">
					<img src="images/icons/sender.png" alt="user">
					<span class="sender">John Doe</span>
					<span class="description">Hi this is just a description...</span>
					<span class="date">24 minutes ago...</span> </a></li>
					<li><a href="#">
					<img src="images/icons/sender.png" alt="user">
					<span class="sender">John Doe</span>
					<span class="description">Hi this is just a description...</span>
					<span class="date">50 minutes ago...</span> </a></li>
					<li id="last"><a href="#" id="all-messages">See all messages!
					<span id="unreaded">8 unreaded.</span> </a></li>
				</ul>
				<br class="clear">
			</div><!-- end messages-box -->
			<a title="Logout" href="#" id="power">logout</a>
		</div>
		<?=$this->adminMenu()?>
	</div>
	<!-- end div#header-top -->
	<?=$this->adminBreadcrumbs()?>
	<!-- end div#search-box -->
</div>
<!-- end header -->
<div id="page-wrap">
	<div id="right-sidebar">
		<?=$this->placeholder('sidebar')?>
	</div>
	<!-- end right-sidebar -->
	<div id="main-content">
		<?=$this->layout()->content?>
	</div>
	<!-- end main-content -->
</div>
<!-- end page-wrap -->
<div id="footer">
	<p>© 2010 Spav.com.pl</p>
</div>
<!-- end footer -->

</body>
</html>