<script type="text/javascript">
<!--
$(document).ready(function(){
	$('#article-form').validate();
	$('#article-form').submit( function(e){
		e.stopPropagation();
		if( $('#article-form').valid() ) {
			var result = client['article.add']($('#article-form').serialize());
			if(client.error) {
				showError('Zapis nie powiódł się :(');
				error_message = jQuery.parseJSON(client.error_message);
				for( var field in error_message ) {
					for( var error in error_message[field] ) {
						$('input[name=name]')
					} 
				}
			} else {
				showSuccess(result);
			}
		} else {
			showError('Wypełnij poprawnie formularz');
		}				
		return false;
	});
});	
//-->
</script>
<div class="innerdiv clear">
	<!-- Tabs -->
	<h2 class="head-alt-white">Nowy artykuł</h2>
	<ul class="tabs">
		<li><a href="<?=$this->baseUrl('cms/articles')?>">Lista</a></li>
		<li><a class="current" href="<?=$this->baseUrl('cms/articles/add')?>">Dodaj nowy</a></li>
	</ul>
	<div class="innercontent">
		<!-- tab "panes" -->
		<div class="panes">
			<div style="display: block;">
				<?=$this->form?>
			</div>
		</div>
	</div>
</div>