<div class="innerdiv clear">
	<!-- Tabs -->
	<h2 class="head-alt-white">Artykuły</h2>
	<ul class="tabs">
		<li><a class="current" href="<?=$this->baseUrl('cms/articles')?>">Lista</a></li>
		<li><a href="<?=$this->baseUrl('cms/articles/add')?>">Dodaj nowy</a></li>
	</ul>
	<div class="innercontent">
		<!-- tab "panes" -->
		<div class="panes">
			<div style="display: block;">
				<table id="article-list" class="full">
					<!-- <thead>
						<tr>
							<th><input type="checkbox" class="check-all"></th>
							<th>Tytuł</th>
							<th>Status</th>
							<th>Adres</th>
							<th>Kategoria</th>
						</tr>
					</thead>-->
					<tfoot>
						<tr>
							<td colspan="6">
								<div class="bulk-actions">
									<select name="dropdown">
									<option value="option1">Wybierz akcję...
									</option>
									<option value="option2">Edytuj</option>
									<option value="option3">Usuń</option>
									<option value="option3">Zatwierdź</option>
									</select> <a href="#" class="button">Wykonaj dla zaznaczonych</a> </div>
								<div class="pagination">
									<a title="First Page" href="#">« Pierwsza</a><a title="Previous Page" href="#">« Poprzednia</a>
									<a title="1" href="#" class="number">1</a>
									<a title="2" href="#" class="number">2</a>
									<a title="3" href="#" class="number">3</a>
									<a title="4" href="#" class="number current">
									4</a>
									<a title="Next Page" href="#" class="disabled-page">
									Następna »</a><a title="Last Page" href="#" class="disabled-page">Ostatnia »</a> </div>
								<!-- End .pagination -->
								<div class="clear">
								</div>
							</td>
						</tr>
					</tfoot>
					<tbody class="tooltip-enabled"></tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
<!--
	$('#article-list').zGrid({
		url: '/rest/articles',
		checkboxes: true,
		controls: true,
		paginator: true,
		pageTag: 'page',
		sortable: true,
		sortTag: 'sort',
		cols: [{
			label: 'Tytuł',
			id: 'name',
			type: 'head',
			sortable: true
		},{
			label: 'Status',
			id: 'status',
			type: 'img',
			sortable: true
		},{
			label: 'Adres',
			id: 'url',
			type: 'url',
			sortable: false
		},{
			label: 'Kategorie',
			id: 'categories',
			type: 'string',
			sortable: false
		}],
		onLoad: function(){
			$('.delete-btn').click( function(e){
				e.stopPropagation();
				var result = client['article.delete'](e.currentTarget.name);
				if(client.error) {
					showError('Usunięcie nie powiódło się :(');
				} else {
					//window.location.reload();
					$('#article-list').zGridDeleteRow(e.currentTarget.name);
					showSuccess(result);
				}
				return false;
			});
		}
	});
//-->
</script>