<script type="text/javascript" src="<?=$this->baseUrl('js/initUserbox.js')?>"></script>

<h1>Logowanie</h1>
<form class="login" name="login" method="POST">
	<p class="message"></p>
	<ul>
		<li>
			<label for="login">login:</label><input type="text" name="login"/>
		</li><li>
			<label for="password">haslo:</label><input type="password" name="password"/>
		</li><li>
			<input type="checkbox" name="rememberme"/><label class="checkbox" for="rememberme">zapamietaj&nbsp;mnie&nbsp;w&nbsp;tej&nbsp;przeglądarce</label>
		</li><li>
			<input type="submit" value="zaloguj"/>
		</li>
	</ul>
</form>