<div id="nav">
	<ul class="sf-menu sf-navbar">
		<li><a id="dashboard" href="#a">Dashboard</a>
		<ul>
			<li><a href="#">dashboard with no submenu, this is description!</a>
			</li>
		</ul>
		</li>

		<li class="current"><a id="articles" href="#a">Articles</a>
		<ul>
			<li class="current"><a href="#aa">write an article</a> </li>
			<li><a href="#ab">manage articles</a>
			<ul>
				<li><a href="#">New Article</a></li>

				<li><a href="#aba">List All</a></li>
				<li><a href="#abb">Add New</a></li>
				<li><a href="#abc">Categorys</a></li>
				<li><a href="#abd">Tags</a></li>
			</ul>
			</li>
			<li><a href="#">categorys</a> </li>

			<li><a href="#">tags</a> </li>
		</ul>
		</li>
		<li><a id="users" href="#">Users</a>
		<ul>
			<li><a href="#">list users</a>
			<ul>

				<li><a href="#">Admins</a></li>
				<li><a href="#">Editors</a></li>
				<li><a href="#">Writers</a></li>
				<li><a href="#">Others</a></li>
			</ul>
			</li>
			<li><a href="#">roles</a>

			<ul>
				<li><a href="#">List Roles</a></li>
				<li><a href="#">Add Role</a></li>
				<li><a href="#">Delete Role</a></li>
				<li><a href="#">Edit Roles</a></li>
			</ul>
			</li>

			<li><a href="#">manage</a> </li>
			<li><a href="#">edit</a> </li>
		</ul>
		</li>
		<li><a id="settings" href="#">Settings</a>
		<ul>

			<li><a href="#">themes</a>
			<ul>
				<li><a href="#">Change Theme</a></li>
				<li><a href="#">Edit Theme</a></li>
			</ul>
			</li>
			<li><a href="#">profile</a>

			<ul>
				<li><a href="#">Profile picture</a></li>
				<li><a href="#">Messages</a></li>
				<li><a href="#">Other Settings</a></li>
			</ul>
			</li>
			<li><a href="#">menu item</a> </li>

			<li><a href="#">menu item</a> </li>
		</ul>
		</li>
	</ul>
</div>
<!-- end div#nav -->