<div id="nav">
	<ul class="sf-menu sf-navbar">
		<li><a id="dashboard" href="<?=$this->baseUrl('cms')?>">Podsumowanie</a>
		<ul>
			<li><a href="<?=$this->baseUrl('cms')?>">wróć do strony głównej panelu</a>
			</li>
		</ul>
		</li>

		<li><a id="articles" href="<?=$this->baseUrl('cms/articles')?>">Artykuły</a>
		<ul>
			<li><a href="cms/articles/add">napisz artykuł</a> </li>
			<li><a href="<?=$this->baseUrl('cms/articles')?>">zarządzaj artykułami</a></li>
			<li><a href="<?=$this->baseUrl('cms/categories')?>">kategorie</a> </li>
		</ul>
		</li>
	</ul>
</div>
<!-- end div#nav -->